-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 20:17:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ocms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocms` ;

-- -----------------------------------------------------
-- Schema ocms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocms` DEFAULT CHARACTER SET utf8 ;
USE `ocms` ;

-- -----------------------------------------------------
-- Table `ocms`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`project` ;

CREATE TABLE IF NOT EXISTS `ocms`.`project` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prj_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checklist` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checklist` (
  `checklist_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `percentage` DOUBLE NULL,
  `project_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`checklist_id`),
  INDEX `fk_checklists_project_idx` (`project_id` ASC),
  CONSTRAINT `fk_checklists_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `ocms`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checkitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checkitem` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checkitem` (
  `checkitem_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `related_item_id` INT NULL,
  `related_goal_id` INT NULL,
  PRIMARY KEY (`checkitem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`item` ;

CREATE TABLE IF NOT EXISTS `ocms`.`item` (
  `item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `percentage` DOUBLE NULL,
  `checklist_id` INT UNSIGNED NOT NULL,
  `parent_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_checklist_idx` (`checklist_id` ASC),
  INDEX `fk_items_item_idx` (`parent_id` ASC),
  CONSTRAINT `fk_items_checklist`
    FOREIGN KEY (`checklist_id`)
    REFERENCES `ocms`.`checklist` (`checklist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_item`
    FOREIGN KEY (`parent_id`)
    REFERENCES `ocms`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checkitem_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checkitem_status` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checkitem_status` (
  `checkitem_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `comment` TEXT NULL,
  `deliverables` VARCHAR(15) NULL,
  `prj_type` INT NULL,
  `importance` INT NULL,
  `description` TEXT NULL,
  `history` DATETIME NULL,
  `problem` INT NULL,
  `checkitem_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`checkitem_status_id`),
  INDEX `fk_chekitem_statuses_checkitem_idx` (`checkitem_id` ASC),
  CONSTRAINT `fk_chekitem_statuses_checkitem`
    FOREIGN KEY (`checkitem_id`)
    REFERENCES `ocms`.`checkitem` (`checkitem_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '\n';


-- -----------------------------------------------------
-- Table `ocms`.`item_checkitem_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`item_checkitem_status` ;

CREATE TABLE IF NOT EXISTS `ocms`.`item_checkitem_status` (
  `item_checkitem_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_id` INT UNSIGNED NOT NULL,
  `checkitem_status_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_checkitem_status_id`),
  INDEX `fk_item_checklists_item_idx` (`item_id` ASC),
  INDEX `fk_item_checklists_checkitem_status_idx` (`checkitem_status_id` ASC),
  CONSTRAINT `fk_item_checklists_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `ocms`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_checklists_checkitem_status`
    FOREIGN KEY (`checkitem_status_id`)
    REFERENCES `ocms`.`checkitem_status` (`checkitem_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
