-- MySQL Script generated by MySQL Workbench
-- 12/08/16 13:30:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ocms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ocms` ;

-- -----------------------------------------------------
-- Schema ocms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ocms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ocms` ;

-- -----------------------------------------------------
-- Table `ocms`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`project` ;

CREATE TABLE IF NOT EXISTS `ocms`.`project` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prj_id` INT UNSIGNED NOT NULL COMMENT 'プロジェクトID',
  `name` VARCHAR(30) NOT NULL COMMENT 'プロジェクト名',
  PRIMARY KEY (`project_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checklist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checklist` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checklist` (
  `checklist_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL COMMENT 'チェックリスト名\n',
  `percentage` DOUBLE NULL COMMENT '得点',
  `project_id` INT UNSIGNED NOT NULL COMMENT '外部キー：\n引用表：project\n外部キー名：fk_checklist_project\n外部キー制限：On update cascade, On delete cascade',
  PRIMARY KEY (`checklist_id`),
  INDEX `fk_checklists_project_idx` (`project_id` ASC),
  CONSTRAINT `fk_checklist_project`
    FOREIGN KEY (`project_id`)
    REFERENCES `ocms`.`project` (`project_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checkitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checkitem` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checkitem` (
  `checkitem_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(100) NULL COMMENT '項目内容',
  `related_item_id` INT NULL COMMENT '関連項目\n',
  `related_goal_id` INT NULL COMMENT '関連ゴール\n',
  `description` VARCHAR(200) NULL COMMENT '補足説明：\nガイド的な情報を付与\n',
  `typical_deliverables` VARCHAR(60) NULL COMMENT '典型的な成果物：\n成果物の例',
  PRIMARY KEY (`checkitem_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`item` ;

CREATE TABLE IF NOT EXISTS `ocms`.`item` (
  `item_id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL COMMENT '項目名',
  `percentage` DOUBLE NULL COMMENT '得点',
  `checklist_id` INT UNSIGNED NULL,
  `parent_id` INT UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ocms`.`checkitem_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ocms`.`checkitem_status` ;

CREATE TABLE IF NOT EXISTS `ocms`.`checkitem_status` (
  `checkitem_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` INT NULL COMMENT '状態\n０：NO　１：YES',
  `comment` VARCHAR(200) NULL COMMENT 'コメント\nユーザが自由にコメント',
  `deliverables` VARCHAR(100) NULL COMMENT 'コメントの根拠となる成果物',
  `prj_type` INT NULL COMMENT 'プロジェクトタイプ\n',
  `importance` INT NULL COMMENT '重要度',
  `history` DATETIME NULL COMMENT '変更履歴',
  `problem` INT NULL COMMENT '不遵守事項有無\n',
  `checkitem_id` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`checkitem_status_id`),
  INDEX `fk_chekitem_statuses_checkitem_idx` (`checkitem_id` ASC),
  INDEX `fk_checkitem_status_item_idx` (`item_id` ASC),
  CONSTRAINT `fk_checkitem_status_checkitem`
    FOREIGN KEY (`checkitem_id`)
    REFERENCES `ocms`.`checkitem` (`checkitem_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_checkitem_status_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `ocms`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
